
import type { AyurvedaProduct } from './types';

export const ayurvedaProducts: AyurvedaProduct[] = [
  {
    id: 'chyawanprash-dabur',
    name: 'Dabur Chyawanprash',
    description: 'Awaleha for boosting immunity, with antioxidants. 1kg jar.',
    price: 350,
    imageUrl: 'https://picsum.photos/seed/ayur1/400/300',
    imageHint: 'chyawanprash jar',
  },
  {
    id: 'himalaya-ashvagandha',
    name: 'Himalaya Ashvagandha Tablets',
    description: 'General wellness tablets, helps in stress relief. 60 tablets.',
    price: 165,
    imageUrl: 'https://picsum.photos/seed/ayur2/400/300',
    imageHint: 'herb supplement bottle',
  },
  {
    id: 'zandu-pancharishta',
    name: 'Zandu Pancharishta',
    description: 'Ayurvedic digestive tonic for indigestion, gas, and acidity. 450ml.',
    price: 130,
    imageUrl: 'https://picsum.photos/seed/ayur3/400/300',
    imageHint: 'ayurvedic tonic bottle',
  },
  {
    id: 'liv-52-ds-tablets',
    name: 'Himalaya Liv.52 DS Tablets',
    description: 'Helps protect the liver against hepatotoxins. 60 tablets.',
    price: 180,
    imageUrl: 'https://picsum.photos/seed/ayur4/400/300',
    imageHint: 'liver supplement box',
  },
  {
    id: 'baidyanath-giloy-guduchi',
    name: 'Baidyanath Giloy Guduchi Tablets',
    description: 'Natural immunity booster, helps in fighting infections. 60 tablets.',
    price: 200,
    imageUrl: 'https://picsum.photos/seed/ayur5/400/300',
    imageHint: 'giloy tablets bottle',
  },
  {
    id: 'dabur-honitus-syrup',
    name: 'Dabur Honitus Herbal Cough Syrup',
    description: 'Provides effective relief from cough, without side-effects. 100ml.',
    price: 95,
    imageUrl: 'https://picsum.photos/seed/ayur6/400/300',
    imageHint: 'cough syrup bottle',
  },
  {
    id: 'himalaya-septilin',
    name: 'Himalaya Septilin Tablets',
    description: 'Builds the body\'s own defense mechanism. 60 tablets.',
    price: 170,
    imageUrl: 'https://picsum.photos/seed/ayur7/400/300',
    imageHint: 'immunity tablets box',
  },
  {
    id: 'patanjali-dant-kanti',
    name: 'Patanjali Dant Kanti Toothpaste',
    description: 'Herbal toothpaste for dental protection. 200g.',
    price: 100,
    imageUrl: 'https://picsum.photos/seed/ayur8/400/300',
    imageHint: 'herbal toothpaste tube',
  },
  {
    id: 'baidyanath-triphala-churna',
    name: 'Baidyanath Triphala Churna',
    description: 'A classic blend for constipation and gentle bowel detox. 500g.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/ayur9/400/300',
    imageHint: 'ayurvedic powder jar',
  },
  {
    id: 'himalaya-gasex',
    name: 'Himalaya Gasex Tablets',
    description: 'For symptomatic control of dyspepsia and indigestion. 100 tablets.',
    price: 130,
    imageUrl: 'https://picsum.photos/seed/ayur10/400/300',
    imageHint: 'digestion tablets',
  },
  {
    id: 'organic-india-tulsi-tea',
    name: 'Organic India Tulsi Green Tea',
    description: 'A blend of Tulsi and Green Tea for stress relief and refreshment. 25 tea bags.',
    price: 190,
    imageUrl: 'https://picsum.photos/seed/ayur11/400/300',
    imageHint: 'herbal tea box',
  },
  {
    id: 'kottakkal-balaswagandhadi-thailam',
    name: 'Kottakkal Balaswagandhadi Thailam',
    description: 'Traditional massage oil for muscle strength and pain relief. 200ml.',
    price: 280,
    imageUrl: 'https://picsum.photos/seed/ayur12/400/300',
    imageHint: 'massage oil bottle',
  },
  {
    id: 'dabur-pudin-hara',
    name: 'Dabur Pudin Hara Pearls',
    description: 'Ayurvedic remedy for gas, indigestion, and stomach ache. 10 pearls.',
    price: 25,
    imageUrl: 'https://picsum.photos/seed/ayur13/400/300',
    imageHint: 'indigestion pearls pack',
  },
  {
    id: 'himalaya-brahmi',
    name: 'Himalaya Brahmi Tablets',
    description: 'Mind wellness tablets, helps improve alertness. 60 tablets.',
    price: 160,
    imageUrl: 'https://picsum.photos/seed/ayur14/400/300',
    imageHint: 'mind wellness tablets',
  },
  {
    id: 'jiva-amla-juice',
    name: 'Jiva Amla Juice',
    description: 'Rich in Vitamin C, boosts immunity and promotes hair health. 1 litre.',
    price: 220,
    imageUrl: 'https://picsum.photos/seed/ayur15/400/300',
    imageHint: 'amla juice bottle',
  },
];


    