import type { Brand } from './types';

export const brands: Brand[] = [
  {
    id: 'dabur',
    name: 'Dabur',
    logoUrl: 'https://picsum.photos/seed/brand1/200/100',
    imageHint: 'Dabur logo',
    description: 'A world leader in Ayurveda with a portfolio of over 250 herbal/ayurvedic products.',
  },
  {
    id: 'himalaya',
    name: 'Himalaya',
    logoUrl: 'https://picsum.photos/seed/brand2/200/100',
    imageHint: 'Himalaya logo',
    description: 'Delivering wellness in every home and in every heart.',
  },
  {
    id: 'zandu',
    name: 'Zandu',
    logoUrl: 'https://picsum.photos/seed/brand3/200/100',
    imageHint: 'Zandu logo',
    description: 'A trusted name in Ayurveda for over a century, offering a wide range of products.',
  },
  {
    id: 'patanjali',
    name: 'Patanjali',
    logoUrl: 'https://picsum.photos/seed/brand4/200/100',
    imageHint: 'Patanjali logo',
    description: 'Providing quality, affordable, and accessible solutions for well-being.',
  },
  {
    id: 'baidyanath',
    name: 'Baidyanath',
    logoUrl: 'https://picsum.photos/seed/brand5/200/100',
    imageHint: 'Baidyanath logo',
    description: 'The most trusted name in Ayurveda, established in 1917.',
  },
  {
    id: 'nestle',
    name: 'Nestlé',
    logoUrl: 'https://picsum.photos/seed/brand6/200/100',
    imageHint: 'Nestle logo',
    description: 'Good food, Good life. A leading nutrition, health and wellness company.',
  },
  {
    id: 'johnson-johnson',
    name: 'Johnson & Johnson',
    logoUrl: 'https://picsum.photos/seed/brand7/200/100',
    imageHint: 'Johnson & Johnson logo',
    description: 'Caring for the world, one person at a time, with a wide range of baby and personal care products.',
  },
  {
    id: 'sebamed',
    name: 'Sebamed',
    logoUrl: 'https://picsum.photos/seed/brand8/200/100',
    imageHint: 'Sebamed logo',
    description: 'Science for healthy skin, with a pH of 5.5.',
  },
  {
    id: 'cetaphil',
    name: 'Cetaphil',
    logoUrl: 'https://picsum.photos/seed/brand9/200/100',
    imageHint: 'Cetaphil logo',
    description: 'Dermatologist-recommended skincare for sensitive skin.',
  },
  {
    id: 'horlicks',
    name: 'Horlicks',
    logoUrl: 'https://picsum.photos/seed/brand10/200/100',
    imageHint: 'Horlicks logo',
    description: "Nourishing the nation's health for over a century.",
  },
  {
    id: 'ensure',
    name: 'Ensure',
    logoUrl: 'https://picsum.photos/seed/brand11/200/100',
    imageHint: 'Ensure logo',
    description: 'Complete, balanced nutrition for strength and energy.',
  },
  {
    id: 'accu-chek',
    name: 'Accu-Chek',
    logoUrl: 'https://picsum.photos/seed/brand12/200/100',
    imageHint: 'Accu-Chek logo',
    description: 'A global leader in blood glucose monitoring systems.',
  },
  {
    id: 'omron',
    name: 'Omron',
    logoUrl: 'https://picsum.photos/seed/brand13/200/100',
    imageHint: 'Omron logo',
    description: 'Advanced technology for health monitoring, including blood pressure monitors.',
  },
  {
    id: 'dettol',
    name: 'Dettol',
    logoUrl: 'https://picsum.photos/seed/brand14/200/100',
    imageHint: 'Dettol logo',
    description: 'Trusted protection from germs for your family.',
  },
  {
    id: 'savlon',
    name: 'Savlon',
    logoUrl: 'https://picsum.photos/seed/brand15/200/100',
    imageHint: 'Savlon logo',
    description: 'Germ protection with a gentle touch.',
  },
];
