
import type { Medication, Condition, Doctor } from './types';

export const medications: Medication[] = [
  {
    id: 'paracetamol-500mg',
    name: 'Paracetamol 500mg',
    description: 'A common pain reliever and fever reducer.',
    imageUrl: 'https://picsum.photos/seed/201/400/300',
    imageHint: 'white pills',
    uses: ['Headache', 'Muscle ache', 'Fever', 'Toothache', 'Cold'],
    sideEffects: [
      'Nausea',
      'Stomach pain',
      'Loss of appetite',
      'Dark urine',
      'Jaundice (yellowing of skin or eyes)',
    ],
    interactions: [
      'Avoid drinking alcohol.',
      'Ask a doctor before use if you have liver disease.',
    ],
    price: 30.5,
    reviews: [
      {
        id: 1,
        author: 'Rohan S.',
        rating: 5,
        comment: 'Very effective for headaches. Works quickly!',
        date: '2023-10-15',
      },
      {
        id: 2,
        author: 'Priya K.',
        rating: 4,
        comment: 'Good for fever, but sometimes upsets my stomach.',
        date: '2023-09-22',
      },
    ],
  },
  {
    id: 'ibuprofen-200mg',
    name: 'Ibuprofen 200mg',
    description:
      'A nonsteroidal anti-inflammatory drug (NSAID) used for pain relief, fever reduction, and inflammation.',
    imageUrl: 'https://picsum.photos/seed/202/400/300',
    imageHint: 'orange pills',
    uses: ['Menstrual cramps', 'Arthritis', 'Migraine', 'Sprains'],
    sideEffects: [
      'Upset stomach',
      'Heartburn',
      'Diarrhea',
      'Dizziness',
      'High blood pressure',
    ],
    interactions: ['Avoid with aspirin', 'May interact with blood thinners.'],
    price: 55.0,
    reviews: [
      {
        id: 1,
        author: 'Amit V.',
        rating: 5,
        comment: 'The only thing that helps my migraines.',
        date: '2023-11-01',
      },
    ],
  },
  {
    id: 'cetirizine-10mg',
    name: 'Cetirizine 10mg',
    description: 'An antihistamine used to relieve allergy symptoms.',
    imageUrl: 'https://picsum.photos/seed/203/400/300',
    imageHint: 'small white pill',
    uses: ['Hay fever', 'Hives', 'Runny nose', 'Itchy eyes', 'Sneezing'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Tiredness', 'Stomach pain'],
    interactions: ['Avoid alcohol and other sedatives.'],
    price: 72.75,
    reviews: [],
  },
  {
    id: 'omeprazole-20mg',
    name: 'Omeprazole 20mg',
    description:
      'A proton pump inhibitor (PPI) that reduces stomach acid.',
    imageUrl: 'https://picsum.photos/seed/204/400/300',
    imageHint: 'capsule pill',
    uses: ['Heartburn', 'Acid reflux (GERD)', 'Stomach ulcers'],
    sideEffects: ['Headache', 'Diarrhea or constipation', 'Gas', 'Nausea'],
    interactions: ['May affect the absorption of certain drugs.'],
    price: 98.2,
    reviews: [
      {
        id: 1,
        author: 'Sunita M.',
        rating: 5,
        comment: 'Life-changing for my acid reflux!',
        date: '2023-08-10',
      },
    ],
  },
  {
    id: 'amoxicillin-500mg',
    name: 'Amoxicillin 500mg',
    description: 'A penicillin antibiotic that fights bacteria.',
    imageUrl: 'https://picsum.photos/seed/205/400/300',
    imageHint: 'pink yellow capsule',
    uses: ['Bacterial infections', 'Strep throat', 'Pneumonia', 'Ear infections'],
    sideEffects: ['Nausea', 'Vomiting', 'Diarrhea', 'Rash'],
    interactions: ['May decrease effectiveness of birth control pills.'],
    price: 120.0,
    reviews: [],
  },
  {
    id: 'atorvastatin-10mg',
    name: 'Atorvastatin 10mg',
    description: 'Used to lower bad cholesterol and fats (such as LDL, triglycerides) and raise good cholesterol (HDL) in the blood.',
    imageUrl: 'https://picsum.photos/seed/206/400/300',
    imageHint: 'white tablet',
    uses: ['High cholesterol', 'Prevention of cardiovascular disease'],
    sideEffects: ['Muscle pain', 'Tiredness', 'Diarrhea', 'Joint pain'],
    interactions: ['Avoid grapefruit juice.', 'Many drug interactions exist.'],
    price: 85.5,
    reviews: [],
  },
  {
    id: 'metformin-500mg',
    name: 'Metformin 500mg',
    description: 'Used to treat high blood sugar levels caused by type 2 diabetes.',
    imageUrl: 'https://picsum.photos/seed/207/400/300',
    imageHint: 'white oblong pill',
    uses: ['Type 2 diabetes'],
    sideEffects: ['Nausea', 'Vomiting', 'Stomach upset', 'Diarrhea', 'Weakness'],
    interactions: ['Avoid alcohol.', 'Iodinated contrast materials.'],
    price: 45.0,
    reviews: [],
  },
  {
    id: 'losartan-50mg',
    name: 'Losartan 50mg',
    description: 'Used to treat high blood pressure (hypertension) and to help protect the kidneys from damage due to diabetes.',
    imageUrl: 'https://picsum.photos/seed/208/400/300',
    imageHint: 'film coated tablet',
    uses: ['High blood pressure', 'Diabetic nephropathy'],
    sideEffects: ['Dizziness', 'Tiredness', 'Low blood pressure'],
    interactions: ['Do not use if pregnant.', 'Avoid potassium supplements.'],
    price: 110.25,
    reviews: [],
  },
  {
    id: 'levothyroxine-50mcg',
    name: 'Levothyroxine 50mcg',
    description: 'Used to treat an underactive thyroid (hypothyroidism).',
    imageUrl: 'https://picsum.photos/seed/209/400/300',
    imageHint: 'small purple pill',
    uses: ['Hypothyroidism'],
    sideEffects: ['Hair loss (temporary)', 'Changes in menstrual periods', 'Headache', 'Nervousness'],
    interactions: ['Take on an empty stomach, 30-60 minutes before breakfast.'],
    price: 60.0,
    reviews: [],
  },
  {
    id: 'amlodipine-5mg',
    name: 'Amlodipine 5mg',
    description: 'A calcium channel blocker used to treat high blood pressure and chest pain (angina).',
    imageUrl: 'https://picsum.photos/seed/210/400/300',
    imageHint: 'small white pill',
    uses: ['High blood pressure', 'Angina'],
    sideEffects: ['Swelling of legs or ankles', 'Tiredness', 'Stomach pain', 'Dizziness'],
    interactions: ['Can interact with certain heart medications.'],
    price: 40.0,
    reviews: [],
  },
  {
    id: 'montelukast-10mg',
    name: 'Montelukast 10mg',
    description: 'Used to prevent wheezing, difficulty breathing, chest tightness, and coughing caused by asthma.',
    imageUrl: 'https://picsum.photos/seed/211/400/300',
    imageHint: 'beige square pill',
    uses: ['Asthma', 'Allergic rhinitis'],
    sideEffects: ['Headache', 'Stomach pain', 'Mood changes', 'Cough'],
    interactions: ['Few major drug interactions.'],
    price: 150.0,
    reviews: [],
  },
  {
    id: 'gabapentin-300mg',
    name: 'Gabapentin 300mg',
    description: 'An anti-epileptic drug, also used to treat nerve pain.',
    imageUrl: 'https://picsum.photos/seed/212/400/300',
    imageHint: 'yellow capsule',
    uses: ['Seizures', 'Nerve pain from shingles', 'Restless legs syndrome'],
    sideEffects: ['Dizziness', 'Drowsiness', 'Loss of coordination', 'Tiredness'],
    interactions: ['Avoid alcohol.', 'Can increase the effect of opioids.'],
    price: 180.50,
    reviews: [],
  },
  {
    id: 'sertraline-50mg',
    name: 'Sertraline 50mg',
    description: 'An SSRI antidepressant used to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and anxiety disorders.',
    imageUrl: 'https://picsum.photos/seed/213/400/300',
    imageHint: 'blue oblong pill',
    uses: ['Depression', 'OCD', 'Panic disorder', 'PTSD', 'Social anxiety disorder'],
    sideEffects: ['Nausea', 'Dizziness', 'Drowsiness', 'Insomnia', 'Loss of appetite'],
    interactions: ['Risk of serotonin syndrome if taken with other serotonergic drugs.'],
    price: 95.0,
    reviews: [],
  },
  {
    id: 'furosemide-20mg',
    name: 'Furosemide 20mg',
    description: 'A diuretic ("water pill") used to treat fluid retention (edema) in people with congestive heart failure, liver disease, or a kidney disorder.',
    imageUrl: 'https://picsum.photos/seed/214/400/300',
    imageHint: 'small white tablet',
    uses: ['Edema', 'High blood pressure'],
    sideEffects: ['Increased urination', 'Thirst', 'Dizziness', 'Muscle cramps'],
    interactions: ['Can cause dehydration and electrolyte imbalance.'],
    price: 25.0,
    reviews: [],
  },
  {
    id: 'pantoprazole-40mg',
    name: 'Pantoprazole 40mg',
    description: 'A proton pump inhibitor (PPI) that decreases the amount of acid produced in the stomach.',
    imageUrl: 'https://picsum.photos/seed/215/400/300',
    imageHint: 'yellow oval pill',
    uses: ['GERD', 'Erosive esophagitis', 'Zollinger-Ellison syndrome'],
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Gas'],
    interactions: ['May reduce the absorption of drugs that need stomach acid.'],
    price: 130.0,
    reviews: [],
  },
];

export const conditions: Condition[] = [
  {
    id: 'diabetes-care',
    name: 'Diabetes Care',
    description: 'Products and information for managing diabetes.',
    imageUrl: 'https://picsum.photos/seed/501/80/80',
    imageHint: 'glucose meter',
    symptoms: ['Increased thirst', 'Frequent urination', 'Unexplained weight loss', 'Fatigue', 'Blurred vision'],
    treatments: ['Blood sugar monitoring', 'Oral medications (e.g., Metformin)', 'Insulin therapy', 'Healthy diet and exercise'],
  },
  {
    id: 'cardiac-care',
    name: 'Cardiac Care',
    description: 'Support your heart health with these products.',
    imageUrl: 'https://picsum.photos/seed/502/80/80',
    imageHint: 'healthy heart',
    symptoms: ['Chest pain', 'Shortness of breath', 'High blood pressure', 'High cholesterol', 'Irregular heartbeat'],
    treatments: ['Blood pressure medication (e.g., Losartan, Amlodipine)', 'Cholesterol-lowering drugs (e.g., Atorvastatin)', 'Lifestyle changes (diet, exercise)', 'Aspirin therapy'],
  },
  {
    id: 'stomach-care',
    name: 'Stomach Care',
    description: 'Find relief for various digestive issues.',
    imageUrl: 'https://picsum.photos/seed/503/80/80',
    imageHint: 'stomach anatomy',
    symptoms: ['Heartburn', 'Acid reflux', 'Nausea', 'Bloating', 'Indigestion'],
    treatments: ['Antacids', 'Proton Pump Inhibitors (e.g., Omeprazole, Pantoprazole)', 'Probiotics', 'Dietary adjustments'],
  },
  {
    id: 'pain-relief',
    name: 'Pain Relief',
    description: 'Alleviate pain from headaches, muscle aches, and more.',
    imageUrl: 'https://picsum.photos/seed/504/80/80',
    imageHint: 'soothing balm',
    symptoms: ['Headaches', 'Muscle soreness', 'Joint pain', 'Menstrual cramps', 'Backache'],
    treatments: ['Pain relievers (e.g., Paracetamol, Ibuprofen)', 'Topical creams and gels', 'Hot/cold packs', 'Physical therapy'],
  },
  {
    id: 'liver-care',
    name: 'Liver Care',
    description: 'Supplements and products to support liver function.',
    imageUrl: 'https://picsum.photos/seed/505/80/80',
    imageHint: 'liver anatomy',
    symptoms: ['Jaundice (yellow skin/eyes)', 'Fatigue', 'Abdominal swelling', 'Nausea', 'Dark urine'],
    treatments: ['Lifestyle changes (avoid alcohol)', 'Hepatitis medications', 'Liver-support supplements (e.g., Milk Thistle)', 'Antiviral drugs'],
  },
  {
    id: 'oral-care',
    name: 'Oral Care',
    description: 'Everything you need for a healthy smile.',
    imageUrl: 'https://picsum.photos/seed/506/80/80',
    imageHint: 'toothbrush toothpaste',
    symptoms: ['Toothache', 'Bleeding gums', 'Bad breath', 'Cavities', 'Mouth sores'],
    treatments: ['Regular brushing and flossing', 'Antiseptic mouthwash', 'Fluoride toothpaste', 'Dental check-ups'],
  },
  {
    id: 'respiratory',
    name: 'Respiratory',
    description: 'Breathe easier with our respiratory care products.',
    imageUrl: 'https://picsum.photos/seed/507/80/80',
    imageHint: 'lungs anatomy',
    symptoms: ['Coughing', 'Wheezing', 'Shortness of breath', 'Chest tightness', 'Nasal congestion'],
    treatments: ['Inhalers (for asthma)', 'Decongestants', 'Cough syrups', 'Antihistamines (e.g., Cetirizine)', 'Nebulizers'],
  },
  {
    id: 'sexual-health',
    name: 'Sexual Health',
    description: 'A range of products for sexual wellness.',
    imageUrl: 'https://picsum.photos/seed/508/80/80',
    imageHint: 'couple silhouette',
    symptoms: ['Erectile dysfunction', 'Low libido', 'Pain during intercourse', 'Sexually transmitted infections (STIs)'],
    treatments: ['Contraceptives', 'Lubricants', 'Medications for ED', 'STI testing and treatment'],
  },
  {
    id: 'elderly-care',
    name: 'Elderly Care',
    description: 'Products tailored for the needs of senior citizens.',
    imageUrl: 'https://picsum.photos/seed/509/80/80',
    imageHint: 'elderly couple',
    symptoms: ['Joint stiffness', 'Memory loss', 'Reduced mobility', 'Incontinence', 'Nutritional deficiencies'],
    treatments: ['Mobility aids (canes, walkers)', 'Adult diapers', 'Nutritional supplements', 'Memory-support supplements'],
  },
  {
    id: 'cold-immunity',
    name: 'Cold & Immunity',
    description: 'Boost your immunity and fight off the common cold.',
    imageUrl: 'https://picsum.photos/seed/510/80/80',
    imageHint: 'orange vitamin',
    symptoms: ['Runny nose', 'Sore throat', 'Sneezing', 'Fever', 'Body aches'],
    treatments: ['Vitamin C & Zinc supplements', 'Herbal remedies (e.g., Echinacea, Tulsi)', 'Decongestants', 'Pain relievers'],
  },
  {
    id: 'skin-care',
    name: 'Skin Care',
    description: 'Solutions for various skin concerns like acne, dryness, and aging.',
    imageUrl: 'https://picsum.photos/seed/511/80/80',
    imageHint: 'skin cream',
    symptoms: ['Acne/Pimples', 'Dry or flaky skin', 'Eczema or rashes', 'Wrinkles', 'Dark spots'],
    treatments: ['Cleansers and moisturizers', 'Acne creams', 'Sunscreens', 'Anti-aging serums', 'Topical ointments'],
  },
  {
    id: 'hair-care',
    name: 'Hair Care',
    description: 'Address hair fall, dandruff, and other scalp issues.',
    imageUrl: 'https://picsum.photos/seed/512/80/80',
    imageHint: 'hair shampoo',
    symptoms: ['Hair loss', 'Dandruff', 'Dry or brittle hair', 'Itchy scalp', 'Split ends'],
    treatments: ['Anti-hair fall shampoos', 'Anti-dandruff shampoos', 'Hair serums and oils', 'Hair growth supplements (e.g., Biotin)'],
  },
  {
    id: 'bone-joint-care',
    name: 'Bone & Joint',
    description: 'Strengthen your bones and manage joint pain.',
    imageUrl: 'https://picsum.photos/seed/513/80/80',
    imageHint: 'human skeleton joint',
    symptoms: ['Joint pain and stiffness', 'Swelling', 'Reduced range of motion', 'Cracking or popping sounds', 'Weak bones (Osteoporosis)'],
    treatments: ['Calcium & Vitamin D supplements', 'Anti-inflammatory drugs (e.g., Ibuprofen)', 'Joint support supplements (Glucosamine)', 'Pain relief oils and sprays'],
  },
  {
    id: 'mental-wellness',
    name: 'Mental Wellness',
    description: 'Products to help manage stress, anxiety, and sleep.',
    imageUrl: 'https://picsum.photos/seed/514/80/80',
    imageHint: 'calm brain',
    symptoms: ['Anxiety', 'Depression', 'Insomnia', 'Stress', 'Difficulty concentrating'],
    treatments: ['Antidepressants (e.g., Sertraline)', 'Anti-anxiety medication', 'Herbal relaxants (e.g., Ashwagandha)', 'Sleep aids'],
  },
  {
    id: 'women-health',
    name: "Women's Health",
    description: "Specific products for women's health needs.",
    imageUrl: 'https://picsum.photos/seed/515/80/80',
    imageHint: 'female symbol',
    symptoms: ['Irregular periods', 'Menstrual cramps', 'Urinary Tract Infections (UTIs)', 'Vaginal infections', 'Menopausal symptoms'],
    treatments: ['Feminine hygiene washes', 'Menstrual products (pads, tampons)', 'UTI remedies (Cranberry extract)', 'Hormonal supplements'],
  },
];

export const doctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Anjali Sharma',
    specialty: 'Cardiologist',
    experience: 15,
    location: 'Bengaluru',
    imageUrl: 'https://picsum.photos/seed/doc1/200/200',
    imageHint: 'female doctor smiling'
  },
  {
    id: 'doc-2',
    name: 'Dr. Vikram Singh',
    specialty: 'Dermatologist',
    experience: 10,
    location: 'Mumbai',
    imageUrl: 'https://picsum.photos/seed/doc2/200/200',
    imageHint: 'male doctor glasses'
  },
  {
    id: 'doc-3',
    name: 'Dr. Priya Desai',
    specialty: 'Pediatrician',
    experience: 12,
    location: 'Delhi',
    imageUrl: 'https://picsum.photos/seed/doc3/200/200',
    imageHint: 'doctor with child'
  },
  {
    id: 'doc-4',
    name: 'Dr. Rohan Gupta',
    specialty: 'Orthopedic Surgeon',
    experience: 20,
    location: 'Bengaluru',
    imageUrl: 'https://picsum.photos/seed/doc4/200/200',
    imageHint: 'male surgeon serious'
  },
  {
    id: 'doc-5',
    name: 'Dr. Meera Krishnan',
    specialty: 'Gynecologist',
    experience: 18,
    location: 'Chennai',
    imageUrl: 'https://picsum.photos/seed/doc5/200/200',
    imageHint: 'female doctor professional'
  },
  {
    id: 'doc-6',
    name: 'Dr. Sameer Joshi',
    specialty: 'Neurologist',
    experience: 14,
    location: 'Pune',
    imageUrl: 'https://picsum.photos/seed/doc6/200/200',
    imageHint: 'male doctor thinking'
  },
  {
    id: 'doc-7',
    name: 'Dr. Aisha Khan',
    specialty: 'Endocrinologist',
    experience: 11,
    location: 'Hyderabad',
    imageUrl: 'https://picsum.photos/seed/doc7/200/200',
    imageHint: 'female doctor hijab'
  },
  {
    id: 'doc-8',
    name: 'Dr. Arjun Reddy',
    specialty: 'General Physician',
    experience: 8,
    location: 'Kolkata',
    imageUrl: 'https://picsum.photos/seed/doc8/200/200',
    imageHint: 'young male doctor'
  },
  {
    id: 'doc-9',
    name: 'Dr. Sneha Patil',
    specialty: 'Psychiatrist',
    experience: 9,
    location: 'Mumbai',
    imageUrl: 'https://picsum.photos/seed/doc9/200/200',
    imageHint: 'female doctor listening'
  },
  {
    id: 'doc-10',
    name: 'Dr. Rajesh Kumar',
    specialty: 'Pulmonologist',
    experience: 16,
    location: 'Delhi',
    imageUrl: 'https://picsum.photos/seed/doc10/200/200',
    imageHint: 'middle-aged male doctor'
  },
  {
    id: 'doc-11',
    name: 'Dr. Sunita Rao',
    specialty: 'Gastroenterologist',
    experience: 13,
    location: 'Bengaluru',
    imageUrl: 'https://picsum.photos/seed/doc11/200/200',
    imageHint: 'indian female doctor'
  },
  {
    id: 'doc-12',
    name: 'Dr. Anand Iyer',
    specialty: 'ENT Specialist',
    experience: 22,
    location: 'Chennai',
    imageUrl: 'https://picsum.photos/seed/doc12/200/200',
    imageHint: 'senior male doctor'
  },
  {
    id: 'doc-13',
    name: 'Dr. Fatima Ahmed',
    specialty: 'Ophthalmologist',
    experience: 7,
    location: 'Pune',
    imageUrl: 'https://picsum.photos/seed/doc13/200/200',
    imageHint: 'doctor with glasses'
  },
  {
    id: 'doc-14',
    name: 'Dr. Karan Malhotra',
    specialty: 'Urologist',
    experience: 19,
    location: 'Mumbai',
    imageUrl: 'https://picsum.photos/seed/doc14/200/200',
    imageHint: 'confident male doctor'
  },
  {
    id: 'doc-15',
    name: 'Dr. Divya Singh',
    specialty: 'Oncologist',
    experience: 17,
    location: 'Delhi',
    imageUrl: 'https://picsum.photos/seed/doc15/200/200',
    imageHint: 'compassionate female doctor'
  }
];

    

    