import type { Medication, Condition } from './types';

export const medications: Medication[] = [
  {
    id: 'paracetamol-500mg',
    name: 'Paracetamol 500mg',
    description: 'A common pain reliever and fever reducer.',
    imageUrl: 'https://picsum.photos/seed/201/400/300',
    imageHint: 'white pills',
    uses: ['Headache', 'Muscle ache', 'Fever', 'Toothache', 'Cold'],
    sideEffects: [
      'Nausea',
      'Stomach pain',
      'Loss of appetite',
      'Dark urine',
      'Jaundice (yellowing of skin or eyes)',
    ],
    interactions: [
      'Avoid drinking alcohol.',
      'Ask a doctor before use if you have liver disease.',
    ],
    price: 30.5,
    reviews: [
      {
        id: 1,
        author: 'Rohan S.',
        rating: 5,
        comment: 'Very effective for headaches. Works quickly!',
        date: '2023-10-15',
      },
      {
        id: 2,
        author: 'Priya K.',
        rating: 4,
        comment: 'Good for fever, but sometimes upsets my stomach.',
        date: '2023-09-22',
      },
    ],
  },
  {
    id: 'ibuprofen-200mg',
    name: 'Ibuprofen 200mg',
    description:
      'A nonsteroidal anti-inflammatory drug (NSAID) used for pain relief, fever reduction, and inflammation.',
    imageUrl: 'https://picsum.photos/seed/202/400/300',
    imageHint: 'orange pills',
    uses: ['Menstrual cramps', 'Arthritis', 'Migraine', 'Sprains'],
    sideEffects: [
      'Upset stomach',
      'Heartburn',
      'Diarrhea',
      'Dizziness',
      'High blood pressure',
    ],
    interactions: ['Avoid with aspirin', 'May interact with blood thinners.'],
    price: 55.0,
    reviews: [
      {
        id: 1,
        author: 'Amit V.',
        rating: 5,
        comment: 'The only thing that helps my migraines.',
        date: '2023-11-01',
      },
    ],
  },
  {
    id: 'cetirizine-10mg',
    name: 'Cetirizine 10mg',
    description: 'An antihistamine used to relieve allergy symptoms.',
    imageUrl: 'https://picsum.photos/seed/203/400/300',
    imageHint: 'small white pill',
    uses: ['Hay fever', 'Hives', 'Runny nose', 'Itchy eyes', 'Sneezing'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Tiredness', 'Stomach pain'],
    interactions: ['Avoid alcohol and other sedatives.'],
    price: 72.75,
    reviews: [],
  },
  {
    id: 'omeprazole-20mg',
    name: 'Omeprazole 20mg',
    description:
      'A proton pump inhibitor (PPI) that reduces stomach acid.',
    imageUrl: 'https://picsum.photos/seed/204/400/300',
    imageHint: 'capsule pill',
    uses: ['Heartburn', 'Acid reflux (GERD)', 'Stomach ulcers'],
    sideEffects: ['Headache', 'Diarrhea or constipation', 'Gas', 'Nausea'],
    interactions: ['May affect the absorption of certain drugs.'],
    price: 98.2,
    reviews: [
      {
        id: 1,
        author: 'Sunita M.',
        rating: 5,
        comment: 'Life-changing for my acid reflux!',
        date: '2023-08-10',
      },
    ],
  },
];

export const conditions: Condition[] = [
  {
    id: 'diabetes-care',
    name: 'Diabetes Care',
    description: 'Products and information for managing diabetes.',
    imageUrl: 'https://picsum.photos/seed/501/80/80',
    imageHint: 'glucose meter',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'cardiac-care',
    name: 'Cardiac Care',
    description: 'Support your heart health with these products.',
    imageUrl: 'https://picsum.photos/seed/502/80/80',
    imageHint: 'healthy heart',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'stomach-care',
    name: 'Stomach Care',
    description: 'Find relief for various digestive issues.',
    imageUrl: 'https://picsum.photos/seed/503/80/80',
    imageHint: 'stomach anatomy',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'pain-relief',
    name: 'Pain Relief',
    description: 'Alleviate pain from headaches, muscle aches, and more.',
    imageUrl: 'https://picsum.photos/seed/504/80/80',
    imageHint: 'soothing balm',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'liver-care',
    name: 'Liver Care',
    description: 'Supplements and products to support liver function.',
    imageUrl: 'https://picsum.photos/seed/505/80/80',
    imageHint: 'liver anatomy',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'oral-care',
    name: 'Oral Care',
    description: 'Everything you need for a healthy smile.',
    imageUrl: 'https://picsum.photos/seed/506/80/80',
    imageHint: 'toothbrush toothpaste',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'respiratory',
    name: 'Respiratory',
    description: 'Breathe easier with our respiratory care products.',
    imageUrl: 'https://picsum.photos/seed/507/80/80',
    imageHint: 'lungs anatomy',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'sexual-health',
    name: 'Sexual Health',
    description: 'A range of products for sexual wellness.',
    imageUrl: 'https://picsum.photos/seed/508/80/80',
    imageHint: 'couple silhouette',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'elderly-care',
    name: 'Elderly Care',
    description: 'Products tailored for the needs of senior citizens.',
    imageUrl: 'https://picsum.photos/seed/509/80/80',
    imageHint: 'elderly couple',
    symptoms: [],
    treatments: [],
  },
  {
    id: 'cold-immunity',
    name: 'Cold & Immunity',
    description: 'Boost your immunity and fight off the common cold.',
    imageUrl: 'https://picsum.photos/seed/510/80/80',
    imageHint: 'orange vitamin',
    symptoms: [],
    treatments: [],
  },
];
