
import type { HealthDevice } from './types';

export const healthDevices: HealthDevice[] = [
  {
    id: 'accu-chek-instant-s',
    name: 'Accu-Chek Instant S Glucometer',
    description: 'Simple to use blood glucose monitor with test strips. Provides results in less than 4 seconds.',
    price: 1299,
    imageUrl: 'https://picsum.photos/seed/hd1/400/300',
    imageHint: 'glucose meter kit',
  },
  {
    id: 'omron-bp-monitor-hem-7120',
    name: 'Omron HEM-7120 BP Monitor',
    description: 'Fully automatic digital blood pressure monitor with cuff wrapping guide and body movement detection.',
    price: 1980,
    imageUrl: 'https://picsum.photos/seed/hd2/400/300',
    imageHint: 'blood pressure monitor',
  },
  {
    id: 'dr-trust-pulse-oximeter',
    name: 'Dr Trust Pulse Oximeter',
    description: 'Measures blood oxygen saturation (SpO2), pulse rate, and perfusion index. Water-resistant.',
    price: 1500,
    imageUrl: 'https://picsum.photos/seed/hd3/400/300',
    imageHint: 'pulse oximeter device',
  },
  {
    id: 'omron-nebulizer-ne-c28',
    name: 'Omron NE-C28 Compressor Nebulizer',
    description: 'Efficient nebulization for respiratory conditions. For both adults and children.',
    price: 2500,
    imageUrl: 'https://picsum.photos/seed/hd4/400/300',
    imageHint: 'nebulizer machine',
  },
  {
    id: 'beurer-infrared-thermometer',
    name: 'Beurer FT 90 Non-Contact Thermometer',
    description: 'Hygienic and safe temperature measurement without skin contact. Fever alarm.',
    price: 2800,
    imageUrl: 'https://picsum.photos/seed/hd5/400/300',
    imageHint: 'infrared thermometer',
  },
  {
    id: 'agaro-steam-inhaler',
    name: 'Agaro Facial Steamer & Inhaler',
    description: '3-in-1 device for steam, vaporization, and sinus relief.',
    price: 450,
    imageUrl: 'https://picsum.photos/seed/hd6/400/300',
    imageHint: 'steam inhaler device',
  },
  {
    id: 'dr-morepen-weighing-scale',
    name: 'Dr. Morepen PS-01 Weighing Scale',
    description: 'Personal digital weighing scale with high precision strain gauge sensor.',
    price: 999,
    imageUrl: 'https://picsum.photos/seed/hd7/400/300',
    imageHint: 'digital weighing scale',
  },
  {
    id: 'jsb-neck-massager',
    name: 'JSB HF155 Neck Massager',
    description: 'Cervical pain relief kneading massager for neck, back, and shoulders.',
    price: 1850,
    imageUrl: 'https://picsum.photos/seed/hd8/400/300',
    imageHint: 'neck massager pillow',
  },
  {
    id: 'flamingo-heating-pad',
    name: 'Flamingo Orthopaedic Heating Belt',
    description: 'Extra long heating pad for back pain, cramps, and muscle soreness.',
    price: 850,
    imageUrl: 'https://picsum.photos/seed/hd9/400/300',
    imageHint: 'heating pad electric',
  },
  {
    id: 'beatxp-deep-tissue-massager',
    name: 'beatXP Bolt Deep Tissue Massage Gun',
    description: 'Full body massager machine with 6 attachments for pain relief.',
    price: 1999,
    imageUrl: 'https://picsum.photos/seed/hd10/400/300',
    imageHint: 'massage gun device',
  },
  {
    id: 'control-d-lancets',
    name: 'Control D Round Lancets',
    description: 'Fine gauge, sterile lancets for virtually painless blood testing. Box of 100.',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/hd11/400/300',
    imageHint: 'blood lancets box',
  },
  {
    id: 'omron-pedometer',
    name: 'Omron HJ-325 Pedometer',
    description: 'Tracks your steps, distance, and calories burned accurately.',
    price: 1200,
    imageUrl: 'https://picsum.photos/seed/hd12/400/300',
    imageHint: 'pedometer device',
  },
  {
    id: 'equinox-hot-water-bottle',
    name: 'Equinox EQ-HT-01 Hot Water Bottle',
    description: 'High-quality rubber hot water bag for pain relief. 2L capacity.',
    price: 350,
    imageUrl: 'https://picsum.photos/seed/hd13/400/300',
    imageHint: 'hot water bottle',
  },
  {
    id: 'medtech-handy-nebulizer',
    name: 'Medtech Handyneb Smart Nebulizer',
    description: 'Compact and portable nebulizer for use at home or on the go.',
    price: 1300,
    imageUrl: 'https://picsum.photos/seed/hd14/400/300',
    imageHint: 'portable nebulizer',
  },
  {
    id: 'rossmax-thermometer-tg380',
    name: 'Rossmax Digital Thermometer TG380',
    description: 'Flexible tip digital thermometer with fever alarm and 10-second reading.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/hd15/400/300',
    imageHint: 'digital thermometer',
  },
];
