
import type { HomeEssential } from './types';

export const homeEssentials: HomeEssential[] = [
  {
    id: 'dettol-hand-wash',
    name: 'Dettol Liquid Hand Wash',
    description: 'Skincare liquid soap refill, protects from 100 illness-causing germs. 1.5L.',
    price: 299,
    imageUrl: 'https://picsum.photos/seed/he1/400/300',
    imageHint: 'hand wash bottle',
  },
  {
    id: 'lizol-disinfectant',
    name: 'Lizol Disinfectant Surface Cleaner',
    description: 'Kills 99.9% germs, removes tough stains. Citrus flavor, 2L.',
    price: 350,
    imageUrl: 'https://picsum.photos/seed/he2/400/300',
    imageHint: 'surface cleaner bottle',
  },
  {
    id: 'savlon-hand-sanitizer',
    name: 'Savlon Hand Sanitizer',
    description: 'Germ protection on the go, without soap. 500ml.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/he3/400/300',
    imageHint: 'hand sanitizer bottle',
  },
  {
    id: 'harpic-toilet-cleaner',
    name: 'Harpic Powerplus Toilet Cleaner',
    description: '10x more yellowish stain removal. Original, 1L.',
    price: 190,
    imageUrl: 'https://picsum.photos/seed/he4/400/300',
    imageHint: 'toilet cleaner bottle',
  },
  {
    id: 'colin-glass-cleaner',
    name: 'Colin Glass and Surface Cleaner',
    description: 'Provides a streak-free shine. 500ml spray bottle.',
    price: 90,
    imageUrl: 'https://picsum.photos/seed/he5/400/300',
    imageHint: 'glass cleaner spray',
  },
  {
    id: 'good-knight-mosquito-repellent',
    name: 'Good Knight Gold Flash Refill',
    description: 'Liquid vaporizer refill for protection against mosquitos. Pack of 2.',
    price: 140,
    imageUrl: 'https://picsum.photos/seed/he6/400/300',
    imageHint: 'mosquito repellent liquid',
  },
  {
    id: 'ariel-matic-detergent',
    name: 'Ariel Matic Top Load Detergent',
    description: 'Washing powder for top load washing machines. 3kg.',
    price: 650,
    imageUrl: 'https://picsum.photos/seed/he7/400/300',
    imageHint: 'detergent powder box',
  },
  {
    id: 'comfort-fabric-conditioner',
    name: 'Comfort After Wash Fabric Conditioner',
    description: 'Gives unbeatable shine and fragrance. Morning Fresh, 860ml.',
    price: 220,
    imageUrl: 'https://picsum.photos/seed/he8/400/300',
    imageHint: 'fabric conditioner bottle',
  },
  {
    id: 'vim-dishwash-gel',
    name: 'Vim Dishwash Liquid Gel',
    description: 'With the power of 100 lemons, cleans tough grease. 750ml.',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/he9/400/300',
    imageHint: 'dishwash gel bottle',
  },
  {
    id: 'scotch-brite-scrub-pad',
    name: 'Scotch-Brite Scrub Pad',
    description: 'Heavy-duty scrub pads for tough stains. Pack of 3.',
    price: 45,
    imageUrl: 'https://picsum.photos/seed/he10/400/300',
    imageHint: 'kitchen scrub pads',
  },
  {
    id: 'hit-cockroach-killer',
    name: 'HIT Cockroach Killer Spray',
    description: 'Instantly kills disease-spreading cockroaches. 400ml.',
    price: 200,
    imageUrl: 'https://picsum.photos/seed/he11/400/300',
    imageHint: 'insect killer spray',
  },
  {
    id: 'odoform-air-freshener',
    name: 'Odoform Air Freshener Blocks',
    description: 'Long-lasting fragrance for bathrooms and cupboards. Pack of 4.',
    price: 120,
    imageUrl: 'https://picsum.photos/seed/he12/400/300',
    imageHint: 'air freshener blocks',
  },
  {
    id: 'presto-garbage-bags',
    name: 'Presto! Oxo-Biodegradable Garbage Bags',
    description: 'Medium size, 19x21 inches. 30 bags per roll, pack of 6.',
    price: 300,
    imageUrl: 'https://picsum.photos/seed/he13/400/300',
    imageHint: 'garbage bags roll',
  },
  {
    id: 'tide-plus-detergent',
    name: 'Tide Plus Double Power Detergent',
    description: 'With a touch of jasmine & rose, for brilliant whites. 1kg.',
    price: 130,
    imageUrl: 'https://picsum.photos/seed/he14/400/300',
    imageHint: 'detergent powder pack',
  },
  {
    id: 'pril-dishwashing-bar',
    name: 'Pril Dishwashing Bar',
    description: 'With active power molecules to remove tough grease. 250g.',
    price: 20,
    imageUrl: 'https://picsum.photos/seed/he15/400/300',
    imageHint: 'dishwashing soap bar',
  },
];
