
import type { PersonalCareProduct } from './types';

export const personalCareProducts: PersonalCareProduct[] = [
  {
    id: 'nivea-body-lotion',
    name: 'Nivea Body Lotion for Dry Skin',
    description: 'Nourishing Body Milk with Almond Oil. 400ml.',
    price: 350,
    imageUrl: 'https://m.media-amazon.com/images/I/51VCw4lYmBL._UF1000,1000_QL80_.jpg',
    imageHint: 'lotion bottle',
  },
  {
    id: 'dove-shampoo',
    name: 'Dove Intense Repair Shampoo',
    description: 'For damaged hair, with Keratin Actives. 650ml.',
    price: 450,
    imageUrl: 'https://m.media-amazon.com/images/I/41mYNA3tXNL.jpg',
    imageHint: 'shampoo bottle',
  },
  {
    id: 'pears-soap',
    name: 'Pears Pure & Gentle Soap',
    description: 'With glycerin and natural oils. Pack of 8.',
    price: 320,
    imageUrl: 'https://m.media-amazon.com/images/I/613wl9rnjoL._UF1000,1000_QL80_.jpg',
    imageHint: 'soap bars',
  },
  {
    id: 'colgate-total-toothpaste',
    name: 'Colgate Total Advanced Toothpaste',
    description: 'Advanced oral care for whole mouth health. 240g combo pack.',
    price: 220,
    imageUrl: 'https://m.media-amazon.com/images/I/71fAc3++hsL.jpg',
    imageHint: 'toothpaste box',
  },
  {
    id: 'gillette-mach3-razor',
    name: 'Gillette Mach3 Manual Shaving Razor',
    description: 'Closer shave, without all the redness. Handle + 2 cartridges.',
    price: 270,
    imageUrl: 'https://m.media-amazon.com/images/I/61o8Ikd2qrL._UF1000,1000_QL80_.jpg',
    imageHint: 'shaving razor pack',
  },
  {
    id: 'listerine-mouthwash',
    name: 'Listerine Cool Mint Mouthwash',
    description: 'Fights germs that cause bad breath, plaque & gingivitis. 500ml.',
    price: 210,
    imageUrl: 'https://m.media-amazon.com/images/I/71njvndq+PL.jpg',
    imageHint: 'mouthwash bottle',
  },
  {
    id: 'neutrogena-sunscreen',
    name: 'Neutrogena Ultra Sheer Sunscreen',
    description: 'Broad Spectrum SPF 50+, non-greasy and water resistant. 88ml.',
    price: 550,
    imageUrl: 'https://m.media-amazon.com/images/I/41XT6-ALAjL._UF1000,1000_QL80_.jpg',
    imageHint: 'sunscreen tube',
  },
  {
    id: 'vaseline-petroleum-jelly',
    name: 'Vaseline Original Petroleum Jelly',
    description: 'Protects and locks in moisture to help dry skin heal. 42g.',
    price: 65,
    imageUrl: 'https://m.media-amazon.com/images/I/51fp48N3DnL._UF1000,1000_QL80_.jpg',
    imageHint: 'petroleum jelly jar',
  },
  {
    id: 'head-shoulders-shampoo',
    name: 'Head & Shoulders Anti-Dandruff Shampoo',
    description: 'Cool Menthol, up to 100% dandruff free. 650ml.',
    price: 480,
    imageUrl: 'https://m.media-amazon.com/images/I/51TmpsUa8pL._UF1000,1000_QL80_.jpg',
    imageHint: 'anti dandruff shampoo',
  },
  {
    id: 'parachutes-coconut-oil',
    name: 'Parachute 100% Pure Coconut Oil',
    description: 'Nourishes hair from within. 600ml bottle.',
    price: 250,
    imageUrl: 'https://m.media-amazon.com/images/I/61fapIFwFmL.jpg',
    imageHint: 'coconut oil bottle',
  },
  {
    id: 'lux-soap-bar',
    name: 'Lux Velvet Glow Soap Bar',
    description: 'With Jasmine & Vitamin E for glowing skin. Pack of 8.',
    price: 280,
    imageUrl: 'https://m.media-amazon.com/images/I/61+wJ-UbX2L._UF1000,1000_QL80_.jpg',
    imageHint: 'beauty soap bars',
  },
  {
    id: 'nivea-deodorant',
    name: 'Nivea Men Fresh Active Deodorant',
    description: '48h fresh feeling with ocean extracts. 150ml.',
    price: 199,
    imageUrl: 'https://m.media-amazon.com/images/I/51QTmyFj5wL.jpg',
    imageHint: 'deodorant spray can',
  },
  {
    id: 'ponds-face-wash',
    name: 'Pond\'s Pure Detox Face Wash',
    description: 'With activated charcoal for pollution-free glow. 200g.',
    price: 240,
    imageUrl: 'https://m.media-amazon.com/images/I/51LNBCOt4JL.jpg',
    imageHint: 'face wash tube',
  },
  {
    id: 'biotique-bio-neem-face-wash',
    name: 'Biotique Bio Neem Purifying Face Wash',
    description: 'Prevents pimples, purifies skin. 150ml.',
    price: 135,
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/5f7da94c-1481-445a-af28-8b4691d150ab.__CR0,0,970,600_PT0_SX970_V1___.jpg',
    imageHint: 'herbal face wash',
  },
  {
    id: 'set-wet-hair-gel',
    name: 'Set Wet Hair Gel for Men',
    description: 'Vertical Hold, for a spiked up look. 100ml.',
    price: 90,
    imageUrl: 'https://m.media-amazon.com/images/I/61+zohZX6BL._UF1000,1000_QL80_.jpg',
    imageHint: 'hair gel tube',
  },
];
