import type { WomenCareProduct } from './types';

export const womenCareProducts: WomenCareProduct[] = [
  {
    id: 'whisper-ultra-clean',
    name: 'Whisper Ultra Clean XL+ Wings',
    description: 'Sanitary pads with 50% longer length for extra protection. 30 pads.',
    price: 320,
    imageUrl: 'https://picsum.photos/seed/wc1/400/300',
    imageHint: 'sanitary pads pack',
  },
  {
    id: 'stayfree-secure-xl',
    name: 'Stayfree Secure XL Cottony Soft',
    description: 'Cottony-soft pads with wings for comfortable, secure fit. 40 pads.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/wc2/400/300',
    imageHint: 'sanitary napkin packet',
  },
  {
    id: 'vwash-plus',
    name: 'Vwash Plus Intimate Hygiene Wash',
    description: 'Expertly formulated to maintain pH balance and prevent irritation. 200ml.',
    price: 360,
    imageUrl: 'https://picsum.photos/seed/wc3/400/300',
    imageHint: 'intimate wash bottle',
  },
  {
    id: 'everteen-bikini-line-hair-remover',
    name: 'Everteen Crème Hair Remover Bikini Line',
    description: 'Specially designed for sensitive skin of bikini line. 50g.',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/wc4/400/300',
    imageHint: 'hair removal cream',
  },
  {
    id: 'sirona-panty-liners',
    name: 'Sirona Panty Liners',
    description: 'For daily discharge, spotting, and urinary incontinence. 40 liners.',
    price: 199,
    imageUrl: 'https://picsum.photos/seed/wc5/400/300',
    imageHint: 'panty liners box',
  },
  {
    id: 'i-pill-emergency-contraceptive',
    name: 'i-pill Emergency Contraceptive Pill',
    description: 'For emergency contraception within 72 hours. 1 tablet.',
    price: 110,
    imageUrl: 'https://picsum.photos/seed/wc6/400/300',
    imageHint: 'emergency pill pack',
  },
  {
    id: 'prega-news-pregnancy-test',
    name: 'Prega News Pregnancy Test Kit',
    description: 'Quick and accurate results in 5 minutes. Pack of 1.',
    price: 55,
    imageUrl: 'https://picsum.photos/seed/wc7/400/300',
    imageHint: 'pregnancy test kit',
  },
  {
    id: 'veet-hair-removal-cream',
    name: 'Veet Hair Removal Cream for Sensitive Skin',
    description: 'Enriched with Aloe Vera and Vitamin E. 100g.',
    price: 140,
    imageUrl: 'https://picsum.photos/seed/wc8/400/300',
    imageHint: 'veet cream tube',
  },
  {
    id: 'himalaya-evecare',
    name: 'Himalaya Evecare Syrup',
    description: 'Ayurvedic syrup for regulating menstrual cycle and relieving symptoms of PMS. 200ml.',
    price: 120,
    imageUrl: 'https://picsum.photos/seed/wc9/400/300',
    imageHint: 'womens health syrup',
  },
  {
    id: 'sirona-menstrual-cup',
    name: 'Sirona Reusable Menstrual Cup',
    description: 'Medium size, made with medical-grade silicone. Rash-free, leak-proof. ',
    price: 399,
    imageUrl: 'https://picsum.photos/seed/wc10/400/300',
    imageHint: 'menstrual cup',
  },
  {
    id: 'folic-acid-tablets',
    name: 'Folic Acid Tablets (5mg)',
    description: 'Essential for women of childbearing age to prevent neural tube defects. 30 tablets.',
    price: 45,
    imageUrl: 'https://picsum.photos/seed/wc11/400/300',
    imageHint: 'folic acid pills',
  },
  {
    id: 'lactational-granules',
    name: 'Galact Lactational Granules',
    description: 'Ayurvedic supplement to enhance breast milk production. Elaichi flavor, 200g.',
    price: 280,
    imageUrl: 'https://picsum.photos/seed/wc12/400/300',
    imageHint: 'lactation supplement jar',
  },
  {
    id: 'calcium-vitamin-d-tablets',
    name: 'Calcium & Vitamin D3 Tablets',
    description: 'For strong bones and to prevent osteoporosis. 60 tablets.',
    price: 250,
    imageUrl: 'https://picsum.photos/seed/wc13/400/300',
    imageHint: 'calcium supplement bottle',
  },
  {
    id: 'iron-supplement-syrup',
    name: 'Iron & Folic Acid Syrup',
    description: 'To treat and prevent iron-deficiency anemia. 200ml.',
    price: 150,
    imageUrl: 'https://picsum.photos/seed/wc14/400/300',
    imageHint: 'iron syrup bottle',
  },
  {
    id: 'cranberry-extract-capsules',
    name: 'Cranberry Extract Capsules',
    description: 'Supports urinary tract health and helps prevent UTIs. 60 capsules.',
    price: 600,
    imageUrl: 'https://picsum.photos/seed/wc15/400/300',
    imageHint: 'cranberry supplement',
  },
];
